### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by HormCodes** [CrystallizeAPI/crystallize-content-transformer#4]
Is it possible to reduce the size?

https://bundlephobia.com/result?p=@crystallize/content-transformer@5.0.0

**Comment by Horm** [comment]
The biggest dependency is `parse5`...
![Screenshot 2019-10-04 at 15 46 41](https://user-images.githubusercontent.com/10332399/66212465-41957780-e6be-11e9-8d59-343033412e39.png)

**Comment by hakonkrogh** [comment]
Not gonna replace parse5 any time soon. It is mostly only used on the server anyways.
